# api/config/packages/api_platform.yaml
api_platform:
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
                
    # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Dto'
